#' GRASP test statistics
#'
#' This function will generate the GRASP test statistics defined as $V_{n,L}$ in Algorithm 2 from the original paper, in the distribution free setting with score function T(x,w) = w
#' @param y n labels $y_j \in \{0, 1\}$ as a vector
#' @param model the model $\hat{\eta}:\chi \to [0,1]$ as a vector of predicted labels, the result of running the model on each x_j.
#' @param L an integer greater than or equal to 1, default to 50
#' @export
fgrasp_statistic <- function(y, model, L=50){
		n <- length(y)
		# Initialize $V_{n,L}$ vector
		VnL <- rep(0,L)
		# Initialize w vector
		w = rep(0,n)
		# Initialize labels vector. This will correspond to the label for w[j]
		labels = rep(0,n)
		for(j in 1: n){
				if(y[j] == 1){
						w[j] <- runif(1,min=0,max=model[j])
				}else{
						w[j] <- runif(1,min=model[j],max=1)
				}
				for(Lj in 1:L){
						if((Lj-1)/L <= w[j] & w[j] <= Lj/L){
								labels[j] <- Lj
						}
				}
		}
		for(l in 1:L){
				VnL[l] <- sum(labels == l)
		}
		return(VnL)
}

#' Asymptotic test statistic
#'
#' This function will generate the asymptotic test statistic $U_0^{asym}$, with a tolerance of 0.
#' This is the case covered with detail in the original GRASP paper.
#' @param VnL the output vector of fgrasp_statistic()
#' @param n the number of datapoints processed to make this statistic
#' @export
u_asym_0 <- function(VnL, n){
		L <- length(VnL)
		u <- L/n * sum((VnL - n/L)^2)
		return(u)
}

#' Finite test statistic
#'
#' This function will generate the finite test statistic $U_0^{finite}$, with a tolerance of 0.
#' This is the case covered with detail in the original GRASP paper.
#' @param VnL the output vector of fgrasp_statistic()
#' @param n the number of datapoints processed to make this statistic
#' @export
u_finite_0 <- function(VnL, n){
		return(u_asym_0(VnL,n)/2)
}

#' Total Variation Distance test statistic
#'
#' This function will return the initial hypothesis test statistic generated by equation(3) in the paper, with $f(t) = 1/2|t-1|$.
#' @param eta the vector of labels in the test data
#' @param eta_hat the vector of labels predicted by the model
#' @export
hypothesis_tv <- function(eta, eta_hat){
		n <- length(eta)
		return(1/n*sum(abs(eta_hat-eta)))
}

#' KL divergence test statistic
#'
#' This function will return the initial hypothesis test statistic generated by equation(3) in the paper, with $f(t) = t log t$.
#' @param eta the vector of labels in the test data
#' @param eta_hat the vector of labels predicted by the model
#' @export
hypothesis_kl <- function(eta, eta_hat){
		n <- length(eta)
		ce <- -1/n * sum(eta * log(eta) + (1-eta) * log(eta))
		ce_hat <- -1/n * sum(eta * log(eta_hat) + (1-eta) * log(1-eta_hat))
		return(ce_hat - ce)
}

#' Hellinger Distance test statistic
#'
#' This function will return the initial hypothesis test statistic generated by equation(3) in the paper, with $f(t) = (\sqrt{t} - 1)^2$.
#' @param eta the vector of labels in the test data
#' @param eta_hat the vector of labels predicted by the model
#' @export
hypothesis_h <- function(eta, eta_hat){
		n <- length(eta)
		return(1/n * sum((sqrt(eta) - sqrt(eta_hat))^2 + (sqrt(1-eta) - sqrt(1-eta_hat))^2))
}
